version: '3.9'
services:
  front:
    image: node:16-alpine
    
    build: ./frontend

    container_name: ng_front
    working_dir: /app
    restart: on-failure

    stdin_open: true
    tty: true

    environment:
      - API_HOST=back
      - API_PORT=3001

    ports:
      - 3000:3000
    depends_on:
      - back
    volumes:
      - ./frontend:/app
  back:
    image: node:16-alpine
    
    container_name: ng_back
    working_dir: /app
    restart: on-failure

    stdin_open: true
    tty: true

    command: sh

    environment:
      - DB_PASSWORD=admin

    ports:
      - 3333:3333
    depends_on:
      - db
    volumes:
      - ./backend:/app

  db:
    image: postgres
    container_name: ng_db
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=database
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local